  name: great test
  on:
    push:
      branches:
        - main
    workflow_dispatch:

  jobs:
    linux-job:
      runs-on: ubuntu-latest
      steps:
        - run: sleep 30

    windows-job:
      runs-on: windows-latest
      steps:
        - run: Start-Sleep -Seconds 30

    macos-job:
      runs-on: macos-latest
      steps:
        - run: sleep 30

